export const AUTH_IDENTITY_OPTIONS = Symbol('AUTH_IDENTITY_OPTIONS');
export const AUTH_IDENTITY_STORAGE_ADAPTER = Symbol('AUTH_IDENTITY_STORAGE_ADAPTER');
export const AUTH_IDENTITY_PASSWORD_HASHER = Symbol('AUTH_IDENTITY_PASSWORD_HASHER');
export const AUTH_IDENTITY_CLOCK = Symbol('AUTH_IDENTITY_CLOCK');
export const AUTH_IDENTITY_ID_GENERATOR = Symbol('AUTH_IDENTITY_ID_GENERATOR');
export const AUTH_IDENTITY_ENCRYPTION = Symbol('AUTH_IDENTITY_ENCRYPTION');

